#[derive(utoipa::OpenApi)]
#[openapi(
    paths(
        crate::routes::health::health,
        crate::routes::users::create_user,
        crate::routes::users::list_users,
        crate::routes::users::get_user,
        crate::routes::users::update_user,
        crate::routes::users::delete_user,
        crate::routes::auth::login,
        crate::routes::cameras::list_cameras,
        crate::routes::cameras::compare_cameras,
        crate::routes::cameras::list_admin_cameras,
        crate::routes::catalog::get_catalog_schema,
        crate::routes::catalog::list_devices,
        crate::routes::catalog::get_device,
        crate::routes::catalog::get_comparison,
        crate::routes::catalog::get_home,
        crate::routes::catalog::list_admin_devices,
        crate::routes::catalog::list_admin_device_brands,
        crate::routes::catalog::get_admin_device,
        crate::routes::catalog::get_admin_device_by_slug,
        crate::routes::catalog::create_device,
        crate::routes::catalog::update_device,
        crate::routes::route_misses::record_route_miss,
        crate::routes::route_misses::list_route_miss_summaries,
        crate::routes::popularity::record_device_selection,
        crate::routes::popularity::list_popular_devices,
    ),
    components(schemas(
        crate::routes::health::HealthResponse,
        crate::dto::CreateUserRequest,
        crate::dto::UpdateUserRequest,
        crate::dto::UserResponse,
        crate::dto::LoginRequest,
        crate::dto::TokenResponse,
        crate::dto::CameraResponse,
        crate::dto::CameraListResponse,
        crate::dto::CameraComparisonResponse,
        crate::error::ErrorEnvelope,
        crate::dto::CatalogSchemaResponse,
        crate::dto::CatalogBrand,
        crate::dto::SpecificationSection,
        crate::dto::SpecificationRow,
        crate::dto::DeviceSummary,
        crate::dto::DeviceDetail,
        crate::dto::DeviceConfiguration,
        crate::dto::DeviceSource,
        crate::dto::SpecValue,
        crate::dto::Pagination,
        crate::dto::DeviceListResponse,
        crate::dto::ComparisonResponse,
        crate::dto::HomeResponse,
        crate::dto::DeviceWriteRequest,
        crate::dto::SpecInput,
        crate::dto::AliasInput,
        crate::dto::SourceInput,
        crate::dto::ConfigurationInput,
        crate::dto::AliasDetail,
        crate::dto::RouteMissCreateRequest,
        crate::dto::RouteMissSummary,
        crate::dto::RouteMissSummaryResponse,
        crate::dto::DeviceSelectionRequest,
        crate::dto::PopularDeviceSummary,
        crate::dto::PopularDevicesResponse,
    )),
    tags(
        (name = "health", description = "Service health"),
        (name = "users", description = "User management"),
        (name = "auth", description = "Authentication"),
        (name = "catalog", description = "Public device catalog"),
        (name = "analytics", description = "Privacy-limited product analytics collection"),
        (name = "admin", description = "Unauthenticated admin write API — no auth gate yet, add one before any real deployment"),
    )
)]
pub struct ApiDoc;
